USE [ERPMega25]
GO

-- ============================================================================
-- PLS.CrudFieldMappings
--
-- One row per writable field on a CRUD-enabled page (PLS.CrudTableMaster).
-- Drives GenericRecordSave/GenericRecordDelete's dynamic INSERT/UPDATE/DELETE
-- and drives GenericMasterPage.jsx's add/edit drawer field rendering, so new
-- simple CRUD pages never need hand-written SQL or a hand-written React form.
--
-- Scope: single-column primary key only (IsKey=1 on exactly one row per
-- PageGroupID) -- composite keys are out of scope, consistent with this
-- engine only targeting simple flat single-table master data.
-- ============================================================================

IF OBJECT_ID('PLS.CrudFieldMappings', 'U') IS NULL
BEGIN
    CREATE TABLE PLS.CrudFieldMappings (
        MappingID    INT IDENTITY(1,1) PRIMARY KEY,
        PageGroupID  VARCHAR(50)  NOT NULL REFERENCES PLS.CrudTableMaster(PageGroupID),
        ColumnName   VARCHAR(150) NOT NULL,                  -- physical column on TargetTable
        JsonKey      VARCHAR(100) NOT NULL,                  -- LineData JSON key sent by the client
        Label        NVARCHAR(150) NOT NULL,                 -- friendly form label
        DataType     VARCHAR(20)  NOT NULL DEFAULT 'string', -- 'string' | 'number' | 'date' | 'bool'
        IsRequired   BIT          NOT NULL DEFAULT 0,
        IsKey        BIT          NOT NULL DEFAULT 0,        -- marks the single-column primary key
        IsIdentity   BIT          NOT NULL DEFAULT 0,        -- key auto-generated by DB -> excluded from INSERT
        SortOrder    INT          NOT NULL DEFAULT 0
    );
END
GO
